### ISSUE TITLE
Intermitent 422 error 

### ISSUE THREAD

**Issue by xde013** [WiserSolutions/gitops-deploy#8]
We intermittently encounter 422 errors thrown by [github](https://www.npmjs.com/package/js-github) dependency when execution the github action using  `WiserSolutions/gitops-deploy@main`

```
jobs:
  promote:
    name: Promoting an image to deploy it to an Environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: WiserSolutions/gitops-deploy@main
        with:
          repository: ${{ inputs.GITOPS_REPO }}
          ref: refs/heads/${{ inputs.DEPLOY_ENVIRONMENT }}
          path: ${{ inputs.GITOPS_REPO_PATH }}
          token: ${{ secrets.WISER_CI_TOKEN }}
          field: ${{ inputs.GITOPS_FIELD }}
          new-version: ${{ inputs.TAG }}
```

A re-run of the the github action seems to solve the issue consistently. It will be great to upgrade the dependency or maybe choose another library to avoid such issue?

![image](https://github.com/WiserSolutions/gitops-deploy/assets/21088699/704e1640-27f7-4057-9437-67a943b7b735)
